# Generated by Django 2.0 on 2020-09-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_auto_20200828_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pekerja',
            },
        ),
    ]
