# Generated by Django 2.0 on 2020-09-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=150)),
            ],
        ),
    ]
