# Generated by Django 2.0 on 2020-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kondisi',
        ),
        migrations.DeleteModel(
            name='Pengerjaan',
        ),
        migrations.AlterField(
            model_name='tugas',
            name='Task',
            field=models.TextField(),
        ),
    ]
