# Generated by Django 2.2 on 2020-08-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sukucadang',
            name='jenis',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sukucadang',
            name='jumlah',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sukucadang',
            name='kendaraan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sukucadang',
            name='tanggal',
            field=models.CharField(max_length=100),
        ),
    ]
