# Generated by Django 2.0 on 2020-09-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0003_pekerja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sparepart', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('harga', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'harga',
            },
        ),
    ]
